import React from 'react';

import {View, Text, Image, StyleSheet, FlatList} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {BigTitle} from '../components/textBase';
import TopNewsItem from '../components/top_news';
import {COLORS} from '../constants/theme';

export default function TopNews({navigation}) {
  const renderNew = ({item}) => (
    <TopNewsItem
      title={item.title}
      abstract={item.abstract}
      url={item.url}
      byline={item.byline}
      created_date={item.created_date}
      multimedia={item.multimedia}
      navigation={navigation}
    />
  );

  return (
    <SafeAreaView
      edges={['left', 'right', 'bottom']}
      style={styles.headerWrappr}>
      <BigTitle text={'WORLD'} />
      <Text style={{color: '#000'}}>Test From TopNews</Text>
      <View>
        <FlatList
          style={{marginTop: 20, marginBottom: 10}}
          data={DATA}
          renderItem={renderNew}
          keyExtractor={item => item.url}
        />
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  headerWrappr: {
    padding: 20,
    flex: 1,
    backgroundColor: COLORS.creme,
    alignItems: 'flex-start',
  },
});

DATA = [
  {
    section: 'world',
    subsection: 'europe',
    title: 'In Washington, Putin’s Nuclear Threats Stir Growing Alarm',
    abstract:
      'In a gathering Cold War atmosphere, American officials are gaming out responses should Russia resort to battlefield nuclear weapons.',
    url: 'https://www.nytimes.com/2022/10/01/world/europe/washington-putin-nuclear-threats.html',
    uri: 'nyt://article/5d9c75fb-d9a8-5fe4-aad8-174185cfae92',
    byline: 'By David E. Sanger, Anton Troianovski and Julian E. Barnes',
    item_type: 'Article',
    updated_date: '2022-10-01T15:28:55-04:00',
    created_date: '2022-10-01T12:30:21-04:00',
    published_date: '2022-10-01T12:30:21-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'United States International Relations',
      'Nuclear Weapons',
      'United States Politics and Government',
      'Russian Invasion of Ukraine (2022)',
    ],
    org_facet: ['Defense Department', 'North Atlantic Treaty Organization'],
    per_facet: [
      'Putin, Vladimir V',
      'Medvedev, Dmitri A',
      'Biden, Joseph R Jr',
    ],
    geo_facet: ['Russia', 'Ukraine'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/10/01/world/01UkraineNuclear01b/merlin_214112745_6dc76f8e-c395-46b2-a815-65d500f5ab5a-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1229,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'President Vladimir V. Putin of Russia displayed on Friday on a screen in Moscow as he addressed the sham annexation of four regions of Ukraine.',
        copyright: 'Alexander Nemenov/Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/01/world/01UkraineNuclear01b/01UkraineNuclear01b-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'President Vladimir V. Putin of Russia displayed on Friday on a screen in Moscow as he addressed the sham annexation of four regions of Ukraine.',
        copyright: 'Alexander Nemenov/Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/01/world/01UkraineNuclear01b/01UkraineNuclear01b-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'President Vladimir V. Putin of Russia displayed on Friday on a screen in Moscow as he addressed the sham annexation of four regions of Ukraine.',
        copyright: 'Alexander Nemenov/Agence France-Presse — Getty Images',
      },
    ],
    short_url: 'https://nyti.ms/3dYW0js',
  },
  {
    section: 'world',
    subsection: 'europe',
    title:
      'Panic, Bribes, Ditched Cars and a Dash on Foot: Portraits of Flight From Russia',
    abstract:
      'A mountain pass into Georgia has become a choke point for Russians fleeing the country, many of them men who faced being drafted and sent to fight in Ukraine.',
    url: 'https://www.nytimes.com/2022/10/01/world/europe/escape-from-russia.html',
    uri: 'nyt://article/02d2dcb6-3930-50f2-b68b-fa5f107fa48a',
    byline: 'By Ksenia Ivanova and Catherine Porter',
    item_type: 'Article',
    updated_date: '2022-10-01T09:31:36-04:00',
    created_date: '2022-10-01T00:01:13-04:00',
    published_date: '2022-10-01T00:01:13-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Russian Invasion of Ukraine (2022)',
      'Refugees and Displaced Persons',
      'Draft and Recruitment (Military)',
    ],
    org_facet: [],
    per_facet: ['Putin, Vladimir V'],
    geo_facet: ['Georgia', 'Caucasus (Russia)'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/00Russia-Georgia-Border01-promo/merlin_214042137_9471481f-7abb-4666-a26d-02c1b5257bfc-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1365,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Sergei with his two children Daniil, 10, and Karina, 10, in a hotel room in Stepatsminda, Georgia.',
        copyright: 'Ksenia Ivanova for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/00Russia-Georgia-Border01-promo/merlin_214042137_9471481f-7abb-4666-a26d-02c1b5257bfc-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'Sergei with his two children Daniil, 10, and Karina, 10, in a hotel room in Stepatsminda, Georgia.',
        copyright: 'Ksenia Ivanova for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/00Russia-Georgia-Border01-promo/00Russia-Georgia-Border01-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Sergei with his two children Daniil, 10, and Karina, 10, in a hotel room in Stepatsminda, Georgia.',
        copyright: 'Ksenia Ivanova for The New York Times',
      },
    ],
    short_url: 'https://nyti.ms/3y7yWG2',
  },

  {
    section: 'world',
    subsection: 'europe',
    title:
      '‘Naked Fear’: A Pipeline Attack Fans Anxiety in a German Village, and Beyond',
    abstract:
      'The act of sabotage has brought the Ukraine war closer, raising anxiety levels and threatening to undermine the Europeans’ resolve to help Ukraine fight on.',
    url: 'https://www.nytimes.com/2022/10/01/world/europe/germany-pipeline-damage-fear.html',
    uri: 'nyt://article/b4db503b-90b7-5b58-9fd4-f66004f0b938',
    byline: 'By Katrin Bennhold',
    item_type: 'Article',
    updated_date: '2022-10-01T09:57:48-04:00',
    created_date: '2022-10-01T09:57:48-04:00',
    published_date: '2022-10-01T09:57:48-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Embargoes and Sanctions',
      'Pipelines',
      'Russian Invasion of Ukraine (2022)',
    ],
    org_facet: ['Nord Stream AG'],
    per_facet: ['Scholz, Olaf (1958- )', 'Putin, Vladimir V'],
    geo_facet: ['Germany', 'Russia', 'Baltic Sea'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30Pipeline-Anxiety01/merlin_214050513_29600545-370a-41d6-93fa-00c78dcdf2cc-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1367,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'The Nord Stream 2 gas pipeline in Lubmin, Germany, on Friday.',
        copyright: 'Laetitia Vancon for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30Pipeline-Anxiety01/30Pipeline-Anxiety01-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'The Nord Stream 2 gas pipeline in Lubmin, Germany, on Friday.',
        copyright: 'Laetitia Vancon for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30Pipeline-Anxiety01/30Pipeline-Anxiety01-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'The Nord Stream 2 gas pipeline in Lubmin, Germany, on Friday.',
        copyright: 'Laetitia Vancon for The New York Times',
      },
    ],
    short_url: 'https://nyti.ms/3CmytlS',
  },
  {
    section: 'business',
    subsection: '',
    title:
      '‘You Can Feel the Fear’: U.K. Borrowers Face Up to a Broken Mortgage Market',
    abstract:
      'The financial turmoil in Britain has led to soaring interest rates, prompting many lenders to withdraw products and stoking worry among homeowners about rising costs.',
    url: 'https://www.nytimes.com/2022/09/30/business/uk-mortgage-markets.html',
    uri: 'nyt://article/5be7567c-d18e-5a7a-9568-8deea748919b',
    byline: 'By Isabella Kwai',
    item_type: 'Article',
    updated_date: '2022-10-01T14:29:56-04:00',
    created_date: '2022-09-30T10:52:18-04:00',
    published_date: '2022-09-30T10:52:18-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Economic Conditions and Trends',
      'Real Estate and Housing (Residential)',
      'Mortgages',
      'British Pound (Currency)',
      'Interest Rates',
      'Banking and Financial Institutions',
      'Inflation (Economics)',
    ],
    org_facet: ['Bank of England'],
    per_facet: [],
    geo_facet: ['Great Britain'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/10/01/world/30uk-mortgage-print/merlin_214055604_cbfa67e2-1bc4-41ca-909f-7badcfc04cf1-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1366,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Laetitia Anne and Maciej Szostek in their rented home in Loughton, England. The loan they were close to securing fell through this week.',
        copyright: 'Andrew Testa for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/01/world/30uk-mortgage-print/merlin_214055604_cbfa67e2-1bc4-41ca-909f-7badcfc04cf1-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'Laetitia Anne and Maciej Szostek in their rented home in Loughton, England. The loan they were close to securing fell through this week.',
        copyright: 'Andrew Testa for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/01/world/30uk-mortgage-print/30uk-mortgage-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Laetitia Anne and Maciej Szostek in their rented home in Loughton, England. The loan they were close to securing fell through this week.',
        copyright: 'Andrew Testa for The New York Times',
      },
    ],
    short_url: 'https://nyti.ms/3T2u0KL',
  },
  {
    section: 'world',
    subsection: 'asia',
    title: 'In China, Living Not ‘With Covid,’ but With ‘Zero Covid’',
    abstract:
      'The country’s strict coronavirus restrictions dictate the patterns of daily life, like waiting in line for frequent Covid tests and stocking up on extra groceries in case of lockdown.',
    url: 'https://www.nytimes.com/2022/10/01/world/asia/china-covid-zero.html',
    uri: 'nyt://article/43c83bc3-d063-5137-80e1-93588744d7b7',
    byline: 'By Vivian Wang',
    item_type: 'Article',
    updated_date: '2022-10-01T09:16:00-04:00',
    created_date: '2022-10-01T05:00:26-04:00',
    published_date: '2022-10-01T05:00:26-04:00',
    material_type_facet: '',
    kicker: 'china dispatch',
    des_facet: [
      'Coronavirus (2019-nCoV)',
      'Quarantines',
      'Shutdowns (Institutional)',
      'Disease Rates',
    ],
    org_facet: [],
    per_facet: [],
    geo_facet: ['China'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/28/world/00china-covid-dispatch-01/00china-covid-dispatch-01-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1366,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'A Covid testing station in Beijing in September. The government ordered testing sites to be within a 15-minute walk in cities.',
        copyright: 'Thomas Peter/Reuters',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/28/world/00china-covid-dispatch-01/00china-covid-dispatch-01-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'A Covid testing station in Beijing in September. The government ordered testing sites to be within a 15-minute walk in cities.',
        copyright: 'Thomas Peter/Reuters',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/28/world/00china-covid-dispatch-01/00china-covid-dispatch-01-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'A Covid testing station in Beijing in September. The government ordered testing sites to be within a 15-minute walk in cities.',
        copyright: 'Thomas Peter/Reuters',
      },
    ],
    short_url: 'https://nyti.ms/3CycOaB',
  },
  {
    section: 'world',
    subsection: 'africa',
    title:
      'New Coup in Burkina Faso Raises Question: Can the Military Bring Back Security?',
    abstract:
      'A military officer removed another military leader who had seized power only eight months ago. Whether he can do better is another question.',
    url: 'https://www.nytimes.com/2022/10/01/world/africa/burkina-faso-coup-uncertainty.html',
    uri: 'nyt://article/52aae4a2-62c2-5c1b-af2e-ba7011e6766d',
    byline: 'By Elian Peltier',
    item_type: 'Article',
    updated_date: '2022-10-01T10:22:03-04:00',
    created_date: '2022-10-01T08:00:41-04:00',
    published_date: '2022-10-01T08:00:41-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      "Coups D'Etat and Attempted Coups D'Etat",
      'Defense and Military Forces',
    ],
    org_facet: [],
    per_facet: ['Damiba, Paul-Henri Sandaogo'],
    geo_facet: ['Burkina Faso', 'Mali'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/10/01/world/01burkina-folo1a/merlin_214118151_db7c0047-8607-4b9b-86ec-80e491f9ad3a-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1365,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'A military vehicle outside Burkina Faso’s national television offices on Saturday in Ouagadougou, the capital. The coup within a coup was announced on national TV.',
        copyright: 'Olympia De Maismont/Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/01/world/01burkina-folo1a/merlin_214118151_db7c0047-8607-4b9b-86ec-80e491f9ad3a-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'A military vehicle outside Burkina Faso’s national television offices on Saturday in Ouagadougou, the capital. The coup within a coup was announced on national TV.',
        copyright: 'Olympia De Maismont/Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/01/world/01burkina-folo1a/01burkina-folo1a-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'A military vehicle outside Burkina Faso’s national television offices on Saturday in Ouagadougou, the capital. The coup within a coup was announced on national TV.',
        copyright: 'Olympia De Maismont/Agence France-Presse — Getty Images',
      },
    ],
    short_url: 'https://nyti.ms/3BWddlz',
  },
  {
    section: 'world',
    subsection: 'europe',
    title:
      'Truss Tried to Reassure Britons With Media Blitz. Her Woes Multiplied.',
    abstract:
      'In a round of interviews, the prime minister showed little sympathy for the pain that high interest rates could inflict on mortgage holders, critics said.',
    url: 'https://www.nytimes.com/2022/09/30/world/europe/truss-bbc-interviews-tax-cuts.html',
    uri: 'nyt://article/dac148ec-db4d-535e-bbdc-102f479a616f',
    byline: 'By Mark Landler',
    item_type: 'Article',
    updated_date: '2022-10-01T01:14:23-04:00',
    created_date: '2022-09-30T12:08:28-04:00',
    published_date: '2022-09-30T12:08:28-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: ['Politics and Government', 'Government Bonds'],
    org_facet: [
      'Bank of England',
      'British Broadcasting Corp',
      'Conservative Party (Great Britain)',
    ],
    per_facet: ['Truss, Elizabeth (1975- )'],
    geo_facet: ['England', 'Great Britain'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30uk-truss/merlin_214003641_16aa61c5-4d45-468e-a4db-958b266a148d-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1370,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Prime Minister Liz Truss’s Conservative Party now trails the opposition Labour Party by 33 percentage points in polling.',
        copyright: 'Maja Smiejkowska/Reuters',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30uk-truss/30uk-truss-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'Prime Minister Liz Truss’s Conservative Party now trails the opposition Labour Party by 33 percentage points in polling.',
        copyright: 'Maja Smiejkowska/Reuters',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30uk-truss/30uk-truss-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Prime Minister Liz Truss’s Conservative Party now trails the opposition Labour Party by 33 percentage points in polling.',
        copyright: 'Maja Smiejkowska/Reuters',
      },
    ],
    short_url: 'https://nyti.ms/3UVgDxp',
  },
  {
    section: 'world',
    subsection: 'americas',
    title:
      'Bolsonaro vs. Lula: Brazil Faces Radically Opposed Options in Divisive Election',
    abstract:
      'Brazilians voting for president on Sunday will choose between two political titans in a contest seen as a major test for one of the world’s largest democracies.',
    url: 'https://www.nytimes.com/2022/10/01/world/americas/bolsanoro-lula-brazil-election.html',
    uri: 'nyt://article/d7a3aeef-4b4d-5d6f-86f2-e63e074cc372',
    byline: 'By Jack Nicas',
    item_type: 'Article',
    updated_date: '2022-10-01T14:20:53-04:00',
    created_date: '2022-10-01T05:00:30-04:00',
    published_date: '2022-10-01T05:00:30-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Elections',
      'Politics and Government',
      'Voting Machines',
      'Voter Fraud (Election Fraud)',
      'Democracy (Theory and Philosophy)',
      'Project Democracy',
    ],
    org_facet: [],
    per_facet: ['Bolsonaro, Jair (1955- )', 'Da Silva, Luiz Inacio Lula'],
    geo_facet: ['Brazil'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/10/02/world/01brazil-vote-top/02BRAZIL-ELECTION-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1365,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'The challenger, former President Luiz Inácio Lula da Silva, left, and the incumbent, President Jair Bolsonaro. Mr. da Silva leads in the polls.',
        copyright:
          'From left: Lalo de Almeida for The New York Times; Victor Moriyama for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/02/world/01brazil-vote-top/02BRAZIL-ELECTION-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'The challenger, former President Luiz Inácio Lula da Silva, left, and the incumbent, President Jair Bolsonaro. Mr. da Silva leads in the polls.',
        copyright:
          'From left: Lalo de Almeida for The New York Times; Victor Moriyama for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/02/world/01brazil-vote-top/02BRAZIL-ELECTION-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'The challenger, former President Luiz Inácio Lula da Silva, left, and the incumbent, President Jair Bolsonaro. Mr. da Silva leads in the polls.',
        copyright:
          'From left: Lalo de Almeida for The New York Times; Victor Moriyama for The New York Times',
      },
    ],
    short_url: 'https://nyti.ms/3E4zErr',
  },
  {
    section: 'world',
    subsection: 'asia',
    title: 'A Year Under the Taliban',
    abstract:
      'A single year of extremist rule has turned life upside down for Afghans, especially women. A photographer who has long called the country home captured the jarring changes.',
    url: 'https://www.nytimes.com/2022/09/30/world/asia/afghanistan-kabul-taliban-women.html',
    uri: 'nyt://article/a8a5c0c3-14f8-5d0a-8c16-d4f52b502a87',
    byline: 'By Kiana Hayeri',
    item_type: 'Article',
    updated_date: '2022-09-30T09:08:28-04:00',
    created_date: '2022-09-30T05:00:34-04:00',
    published_date: '2022-09-30T05:00:34-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Afghanistan War (2001- )',
      'Women and Girls',
      'Demonstrations, Protests and Riots',
    ],
    org_facet: ['Taliban'],
    per_facet: [],
    geo_facet: ['Afghanistan', 'Kabul (Afghanistan)'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/08/28/world/00afghan-kabul-dispatch-promo/00afghan-kabul-dispatch-2-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1365,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Kiana Hayeri for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/08/28/world/00afghan-kabul-dispatch-promo/00afghan-kabul-dispatch-2-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Kiana Hayeri for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/08/28/world/00afghan-kabul-dispatch-promo/00afghan-kabul-dispatch-2-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Kiana Hayeri for The New York Times',
      },
    ],
    short_url: 'https://nyti.ms/3LVGJMX',
  },
  {
    section: 'world',
    subsection: 'europe',
    title:
      'French Feminist Rabbi Captivates Multifaith Crowds With Musings on Mortality',
    abstract:
      'With Paris locked down over Passover, a rabbi started holding weekly talks over Zoom about Jewish texts. Thousands have tuned in to hear her reflections on death. “She is my rabbi,” said an atheist.',
    url: 'https://www.nytimes.com/2022/09/30/world/europe/delphine-horvilleur-rabbi-judaism.html',
    uri: 'nyt://article/0bbb4cdb-f884-581c-a16a-33abc9809019',
    byline: 'By Julia Lieblich',
    item_type: 'Article',
    updated_date: '2022-10-01T15:24:00-04:00',
    created_date: '2022-09-30T05:00:20-04:00',
    published_date: '2022-09-30T05:00:20-04:00',
    material_type_facet: '',
    kicker: 'The Saturday Profile',
    des_facet: [
      'Content Type: Personal Profile',
      'Rabbis',
      'Jews and Judaism',
      'Death and Dying',
      'Religion and Belief',
      'Videophones and Videoconferencing',
      'Quarantine (Life and Culture)',
    ],
    org_facet: [],
    per_facet: ['Horvilleur, Delphine'],
    geo_facet: ['Paris (France)'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30french-rabbi-profile04/merlin_213842232_fbf08bbf-fef2-4f95-8dd0-30e3edfc926a-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1365,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Rabbi Delphine Horvilleur, center left, in black clothes, attends a Bar Mitzvah ceremony.',
        copyright: 'Mauricio Lima for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30french-rabbi-profile04/merlin_213842232_fbf08bbf-fef2-4f95-8dd0-30e3edfc926a-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'Rabbi Delphine Horvilleur, center left, in black clothes, attends a Bar Mitzvah ceremony.',
        copyright: 'Mauricio Lima for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30french-rabbi-profile04/30french-rabbi-profile04-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Rabbi Delphine Horvilleur, center left, in black clothes, attends a Bar Mitzvah ceremony.',
        copyright: 'Mauricio Lima for The New York Times',
      },
    ],
    short_url: 'https://nyti.ms/3UPEiPV',
  },
  {
    section: 'world',
    subsection: 'asia',
    title: 'Blast at Education Center in Kabul Kills at Least 19',
    abstract:
      'The violence was the latest to target the country’s Hazara ethnic minority and increased fears about the Taliban’s ability to provide security for all of their citizens.',
    url: 'https://www.nytimes.com/2022/09/30/world/asia/afghanistan-bombing-girls-education.html',
    uri: 'nyt://article/6a11c155-b9de-5d99-9c4c-95c356be67e9',
    byline: 'By Yaqoob Akbary and Christina Goldbaum',
    item_type: 'Article',
    updated_date: '2022-10-01T15:25:29-04:00',
    created_date: '2022-09-30T06:21:07-04:00',
    published_date: '2022-09-30T06:21:07-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Terrorism',
      'Hazaras (Ethnic Group)',
      'Civilian Casualties',
      'Education (K-12)',
      'Women and Girls',
    ],
    org_facet: ['Islamic State Khorasan', 'Taliban'],
    per_facet: [],
    geo_facet: ['Kabul (Afghanistan)', 'Afghanistan'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30afghanistan-explosion-01/merlin_214051458_7cbd6135-1092-456e-ac64-54fe58fc5daf-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1366,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Relatives and medical staff tending to one of the victims of an attack on a learning center Friday in the Dasht-e-Barchi neighborhood in Kabul.',
        copyright: 'Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30afghanistan-explosion-01/merlin_214051458_7cbd6135-1092-456e-ac64-54fe58fc5daf-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'Relatives and medical staff tending to one of the victims of an attack on a learning center Friday in the Dasht-e-Barchi neighborhood in Kabul.',
        copyright: 'Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30afghanistan-explosion-01/30afghanistan-explosion-01-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Relatives and medical staff tending to one of the victims of an attack on a learning center Friday in the Dasht-e-Barchi neighborhood in Kabul.',
        copyright: 'Agence France-Presse — Getty Images',
      },
    ],
    short_url: 'https://nyti.ms/3rhXo3x',
  },
  {
    section: 'world',
    subsection: 'middleeast',
    title:
      'Even as Iranians Rise Up, Protests Worldwide Are Failing at Record Rates',
    abstract:
      'Mass protests, once a grave threat to even the fiercest autocrat, have plummeted in effectiveness, a study shows. Factors appear to include polarization, social media and rising nationalist attitudes.',
    url: 'https://www.nytimes.com/2022/09/30/world/middleeast/iran-protests-haiti-russia-china.html',
    uri: 'nyt://article/c63b764c-8d64-5468-95ce-f3ef2ca391d4',
    byline: 'By Max Fisher',
    item_type: 'Article',
    updated_date: '2022-10-01T00:54:38-04:00',
    created_date: '2022-09-30T05:00:22-04:00',
    published_date: '2022-09-30T05:00:22-04:00',
    material_type_facet: '',
    kicker: 'The Interpreter',
    des_facet: [
      'Demonstrations, Protests and Riots',
      'Democracy (Theory and Philosophy)',
      'Politics and Government',
    ],
    org_facet: [],
    per_facet: [],
    geo_facet: [
      'Iran',
      'Indonesia',
      'Haiti',
      'Canada',
      'Chile',
      'China',
      'Sri Lanka',
      'Sudan',
      'United States',
    ],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30Int-Iran01/merlin_213594909_356f2ad4-ca92-41d2-ace2-72f5f617fb15-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 720,
        width: 1080,
        type: 'image',
        subtype: 'photo',
        caption:
          'Iranian demonstrators in the streets of the capital, Tehran, last week. Protests erupted around the country after the death of a young woman, Mahsa Amini, following her detainment in police custody.',
        copyright: 'Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30Int-Iran01/merlin_213594909_356f2ad4-ca92-41d2-ace2-72f5f617fb15-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'Iranian demonstrators in the streets of the capital, Tehran, last week. Protests erupted around the country after the death of a young woman, Mahsa Amini, following her detainment in police custody.',
        copyright: 'Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30Int-Iran01/30Int-Iran01-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Iranian demonstrators in the streets of the capital, Tehran, last week. Protests erupted around the country after the death of a young woman, Mahsa Amini, following her detainment in police custody.',
        copyright: 'Agence France-Presse — Getty Images',
      },
    ],
    short_url: 'https://nyti.ms/3URp4d1',
  },
  {
    section: 'world',
    subsection: 'americas',
    title: 'What to Know About Brazil’s Election',
    abstract:
      'Jair Bolsonaro has questioned the integrity of Sunday’s election and trails in polls to Luiz Inácio Lula da Silva, a leftist and former president, who was imprisoned amid a corruption scandal.',
    url: 'https://www.nytimes.com/2022/09/30/world/americas/brazil-election-bolsonaro-lula.html',
    uri: 'nyt://article/52d23a32-7999-57e3-a00b-2d63151e7fbd',
    byline: 'By Ana Ionova',
    item_type: 'Article',
    updated_date: '2022-10-01T10:49:13-04:00',
    created_date: '2022-09-30T08:14:38-04:00',
    published_date: '2022-09-30T08:14:38-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: ['Elections'],
    org_facet: [],
    per_facet: ['Bolsonaro, Jair (1955- )', 'Da Silva, Luiz Inacio Lula'],
    geo_facet: ['Brazil', 'Latin America'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/10/02/world/02BRAZIL-ELECTION-COMBO/02BRAZIL-ELECTION-COMBO-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1365,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'President Jair Bolsonaro, left, faces a challenge from Luiz Inácio Lula da Silva, a former leftist president.',
        copyright:
          'Victor Moriyama for The New York Times; Dado Galdieri for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/02/world/02BRAZIL-ELECTION-COMBO/02BRAZIL-ELECTION-COMBO-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'President Jair Bolsonaro, left, faces a challenge from Luiz Inácio Lula da Silva, a former leftist president.',
        copyright:
          'Victor Moriyama for The New York Times; Dado Galdieri for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/02/world/02BRAZIL-ELECTION-COMBO/02BRAZIL-ELECTION-COMBO-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'President Jair Bolsonaro, left, faces a challenge from Luiz Inácio Lula da Silva, a former leftist president.',
        copyright:
          'Victor Moriyama for The New York Times; Dado Galdieri for The New York Times',
      },
    ],
    short_url: 'https://nyti.ms/3y41WOG',
  },
  {
    section: 'world',
    subsection: 'europe',
    title: 'Putin supporters are enraged by the Russian retreat from Lyman.',
    abstract:
      'The criticism of the Kremlin after Russia retreated from the key rail hub on Saturday came not just from pro-war commentators on social media, but from two senior allies of Mr. Putin.',
    url: 'https://www.nytimes.com/2022/10/01/world/europe/lyman-russia-retreat-putin.html',
    uri: 'nyt://article/80fbc89e-0bab-576c-ba6e-361bf208566e',
    byline: 'By Anton Troianovski',
    item_type: 'Article',
    updated_date: '2022-10-01T15:12:30-04:00',
    created_date: '2022-10-01T13:55:47-04:00',
    published_date: '2022-10-01T13:55:47-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: ['Russian Invasion of Ukraine (2022)'],
    org_facet: [],
    per_facet: [],
    geo_facet: [],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/11/01/world/01ukraine-briefing-russia-anger02sub/01ukraine-briefing-russia-anger02sub-superJumbo-v4.jpg',
        format: 'Super Jumbo',
        height: 2048,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Ramzan Kadyrov in Chechnya’s regional capital of Grozny, Russia, in March.',
        copyright: 'Associated Press',
      },
      {
        url: 'https://static01.nyt.com/images/2022/11/01/world/01ukraine-briefing-russia-anger02sub/01ukraine-briefing-russia-anger02sub-threeByTwoSmallAt2X-v4.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'Ramzan Kadyrov in Chechnya’s regional capital of Grozny, Russia, in March.',
        copyright: 'Associated Press',
      },
      {
        url: 'https://static01.nyt.com/images/2022/11/01/world/01ukraine-briefing-russia-anger02sub/01ukraine-briefing-russia-anger02sub-thumbLarge-v4.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Ramzan Kadyrov in Chechnya’s regional capital of Grozny, Russia, in March.',
        copyright: 'Associated Press',
      },
    ],
    short_url: 'https://nyti.ms/3fz4fDf',
  },
  {
    section: 'world',
    subsection: 'africa',
    title: 'Uganda Races to Contain a Deadly Ebola Outbreak',
    abstract:
      'The outbreak was caused by the Sudan strain of the virus, which has no approved vaccine or drug treatment. Scientists are now rushing to begin clinical trials in the coming weeks.',
    url: 'https://www.nytimes.com/2022/10/01/world/africa/uganda-ebola-outbreak.html',
    uri: 'nyt://article/4a360242-553e-5a9f-9323-73ca7faf8310',
    byline: 'By Abdi Latif Dahir',
    item_type: 'Article',
    updated_date: '2022-10-01T12:27:24-04:00',
    created_date: '2022-10-01T12:27:24-04:00',
    published_date: '2022-10-01T12:27:24-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: ['Ebola Virus'],
    org_facet: ['World Health Organization'],
    per_facet: ['Museveni, Yoweri'],
    geo_facet: [
      'Uganda',
      'Kampala (Uganda)',
      'Congo, Democratic Republic of (Congo-Kinshasa)',
      'Sudan',
    ],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/00Uganda-Ebola/merlin_213739467_c547c41e-83d3-4aa7-b5dc-6de02daac221-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1364,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Members of the Ebola treatment unit this past week at Mubende Regional Referral Hospital in Uganda.',
        copyright: 'Badru Katumba/Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/00Uganda-Ebola/merlin_213739467_c547c41e-83d3-4aa7-b5dc-6de02daac221-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'Members of the Ebola treatment unit this past week at Mubende Regional Referral Hospital in Uganda.',
        copyright: 'Badru Katumba/Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/00Uganda-Ebola/merlin_213739467_c547c41e-83d3-4aa7-b5dc-6de02daac221-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Members of the Ebola treatment unit this past week at Mubende Regional Referral Hospital in Uganda.',
        copyright: 'Badru Katumba/Agence France-Presse — Getty Images',
      },
    ],
    short_url: 'https://nyti.ms/3y8JsNg',
  },
  {
    section: 'business',
    subsection: '',
    title:
      'Backing Lindt, Swiss Court Orders Lidl to ‘Destroy’ Its Chocolate Bunnies',
    abstract:
      'With Easter still far away, there are none to melt down. But the decision opened a door on the bunny-eat-bunny world of European chocolatiers.',
    url: 'https://www.nytimes.com/2022/10/01/business/lindt-lidl-chocolate-bunnies.html',
    uri: 'nyt://article/ccc8ba85-68b5-5b98-858a-7f1900ee049a',
    byline: 'By Michael Levenson',
    item_type: 'Article',
    updated_date: '2022-10-01T09:00:05-04:00',
    created_date: '2022-10-01T09:00:05-04:00',
    published_date: '2022-10-01T09:00:05-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Suits and Litigation (Civil)',
      'Chocolate',
      'Decisions and Verdicts',
    ],
    org_facet: ['Lidl', 'Lindt & Sprungli AG'],
    per_facet: [],
    geo_facet: ['Switzerland'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/10/03/multimedia/03xp-chocolatebunnies-skybox1/30xp-chocolatebunnies-1-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1366,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Lindt, the Swiss chocolate maker, is protective of its “Gold Bunny.”',
        copyright: 'Arnd Wiegmann/Reuters',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/03/multimedia/03xp-chocolatebunnies-skybox1/30xp-chocolatebunnies-1-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'Lindt, the Swiss chocolate maker, is protective of its “Gold Bunny.”',
        copyright: 'Arnd Wiegmann/Reuters',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/03/multimedia/03xp-chocolatebunnies-skybox1/30xp-chocolatebunnies-1-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Lindt, the Swiss chocolate maker, is protective of its “Gold Bunny.”',
        copyright: 'Arnd Wiegmann/Reuters',
      },
    ],
    short_url: 'https://nyti.ms/3SlKCgp',
  },
  {
    section: 'world',
    subsection: 'europe',
    title:
      'Broken glass, blown-out tires and a crater show the violence of a deadly attack in Zaporizhzhia.',
    abstract:
      'The strike hit a convoy of people fleeing fighting, killing at least 30.',
    url: 'https://www.nytimes.com/2022/10/01/world/europe/zaporizhzhia-strike.html',
    uri: 'nyt://article/319134f7-1927-5f84-b6f8-6802d8bf2073',
    byline: 'By Matthew Mpoke Bigg and Andrew E. Kramer',
    item_type: 'Article',
    updated_date: '2022-10-01T13:49:21-04:00',
    created_date: '2022-10-01T08:56:46-04:00',
    published_date: '2022-10-01T08:56:46-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: ['Russian Invasion of Ukraine (2022)'],
    org_facet: [],
    per_facet: [],
    geo_facet: [],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/10/01/world/01Zaporizhzhia-briefing-01/merlin_214062954_140b64a9-74a4-493a-b3c5-e7717a5a07d2-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1364,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Ukrainian servicemen walk by a crater left by a missile strike near Zaporizhzhia on Friday.',
        copyright: 'Genya Savilov/Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/01/world/01Zaporizhzhia-briefing-01/01Zaporizhzhia-briefing-01-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'Ukrainian servicemen walk by a crater left by a missile strike near Zaporizhzhia on Friday.',
        copyright: 'Genya Savilov/Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/01/world/01Zaporizhzhia-briefing-01/01Zaporizhzhia-briefing-01-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Ukrainian servicemen walk by a crater left by a missile strike near Zaporizhzhia on Friday.',
        copyright: 'Genya Savilov/Agence France-Presse — Getty Images',
      },
    ],
    short_url: 'https://nyti.ms/3y6WLxN',
  },
  {
    section: 'briefing',
    subsection: '',
    title: 'Making Friends',
    abstract:
      'A psychologist and friendship expert has advice for how to make friends as an adult.',
    url: 'https://www.nytimes.com/2022/10/01/briefing/making-friends.html',
    uri: 'nyt://article/e451c4a9-d13d-5b11-8114-ffb4c82a5f47',
    byline: 'By Melissa Kirsch',
    item_type: 'Article',
    updated_date: '2022-10-01T06:23:45-04:00',
    created_date: '2022-10-01T06:23:45-04:00',
    published_date: '2022-10-01T06:23:45-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'internal-storyline-no',
      'Friendship',
      'Psychology and Psychologists',
    ],
    org_facet: [],
    per_facet: [],
    geo_facet: [],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/10/01/multimedia/01-THE-MORNING-NL-PROMO/01-THE-MORNING-NL-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 2048,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'María Jesús Contreras',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/01/multimedia/01-THE-MORNING-NL-PROMO/01-THE-MORNING-NL-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'María Jesús Contreras',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/01/multimedia/01-THE-MORNING-NL-PROMO/01-THE-MORNING-NL-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'María Jesús Contreras',
      },
    ],
    short_url: 'https://nyti.ms/3E5Mx4v',
  },
  {
    section: 'world',
    subsection: 'canada',
    title:
      'Alberta Revives Its Long-Running Campaign Against Federal Gun Controls',
    abstract:
      'Alberta, later followed by Saskatchewan, has directed Mounties in the province not to participate in a buyback program for banned rifles.',
    url: 'https://www.nytimes.com/2022/10/01/world/canada/alberta-revives-its-long-running-campaign-against-federal-gun-controls.html',
    uri: 'nyt://article/6b401a27-4f00-581e-b5d2-40f904be3dd6',
    byline: 'By Ian Austen',
    item_type: 'Article',
    updated_date: '2022-10-01T06:00:02-04:00',
    created_date: '2022-10-01T06:00:02-04:00',
    published_date: '2022-10-01T06:00:02-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: ['Firearms', 'Gun Control'],
    org_facet: ['Royal Canadian Mounted Police'],
    per_facet: [],
    geo_facet: ['Alberta (Canada)', 'Canada'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/10/01/world/01canada-letter/merlin_135247344_d45fca2e-ad5c-4974-aae7-41cf01eae407-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1366,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Alberta has instructed Mounties within its border to not buy back banned rifles.',
        copyright: 'Valerie Zink/Reuters',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/01/world/01canada-letter/merlin_135247344_d45fca2e-ad5c-4974-aae7-41cf01eae407-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'Alberta has instructed Mounties within its border to not buy back banned rifles.',
        copyright: 'Valerie Zink/Reuters',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/01/world/01canada-letter/01canada-letter-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Alberta has instructed Mounties within its border to not buy back banned rifles.',
        copyright: 'Valerie Zink/Reuters',
      },
    ],
    short_url: 'https://nyti.ms/3SJNhjR',
  },
  {
    section: 'world',
    subsection: 'asia',
    title:
      'Battered by Floods and Trapped in Debt, Pakistani Farmers Struggle to Survive',
    abstract:
      'The recent flooding has plunged small farmers in sharecropping arrangements further into debt with their landlords — a cycle that has worsened as extreme weather events become increasingly common.',
    url: 'https://www.nytimes.com/2022/10/01/world/asia/pakistan-flood-farmers.html',
    uri: 'nyt://article/d25d98bc-b544-5595-b051-37eae96306a5',
    byline: 'By Christina Goldbaum, Zia ur-Rehman and Kiana Hayeri',
    item_type: 'Article',
    updated_date: '2022-10-01T06:59:22-04:00',
    created_date: '2022-10-01T05:00:34-04:00',
    published_date: '2022-10-01T05:00:34-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Floods',
      'Agriculture and Farming',
      'Global Warming',
      'Grain',
      'Cotton',
      'Weather',
    ],
    org_facet: [],
    per_facet: [],
    geo_facet: ['Pakistan', 'Sindh Province (Pakistan)'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/10/01/world/01pakistan-farmers-promo/merlin_213446415_06575971-1d8f-403b-b4ba-48bc074af3cf-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1365,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Kiana Hayeri for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/01/world/01pakistan-farmers-promo/merlin_213446415_06575971-1d8f-403b-b4ba-48bc074af3cf-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Kiana Hayeri for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/10/01/world/01pakistan-farmers-promo/01pakistan-farmers-3-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Kiana Hayeri for The New York Times',
      },
    ],
    short_url: 'https://nyti.ms/3CycWqB',
  },
  {
    section: 'world',
    subsection: 'asia',
    title: 'North Korea Launches Two Ballistic Missiles, Fourth Test in a Week',
    abstract:
      'The test came a day after the United States, Japan and South Korea conducted their first joint anti-submarine exercise in five years.',
    url: 'https://www.nytimes.com/2022/09/30/world/asia/north-korea-ballistic-missile-test.html',
    uri: 'nyt://article/c641faeb-9984-5433-9f13-e825a8dd5d0a',
    byline: 'By Choe Sang-Hun',
    item_type: 'Article',
    updated_date: '2022-10-01T01:13:45-04:00',
    created_date: '2022-09-30T20:40:53-04:00',
    published_date: '2022-09-30T20:40:53-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Defense and Military Forces',
      'Missiles and Missile Defense Systems',
      'Nuclear Weapons',
      'Nuclear Tests',
      'United States International Relations',
      'War and Armed Conflicts',
    ],
    org_facet: [],
    per_facet: ['Kim Jong-un', 'Yoon Suk-yeol'],
    geo_facet: ['North Korea', 'South Korea'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30nkorea-01-1-ee31/30nkorea-01-1-ee31-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1366,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Commuters in a train station on Seoul on Friday pass a screen airing news about a recent North Korean ballistic missile launch.',
        copyright: 'Jeon Heon-Kyun/EPA, via Shutterstock',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30nkorea-01-1-ee31/30nkorea-01-1-ee31-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'Commuters in a train station on Seoul on Friday pass a screen airing news about a recent North Korean ballistic missile launch.',
        copyright: 'Jeon Heon-Kyun/EPA, via Shutterstock',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30nkorea-01-1-ee31/30nkorea-01-1-ee31-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Commuters in a train station on Seoul on Friday pass a screen airing news about a recent North Korean ballistic missile launch.',
        copyright: 'Jeon Heon-Kyun/EPA, via Shutterstock',
      },
    ],
    short_url: 'https://nyti.ms/3St7XwM',
  },
  {
    section: 'us',
    subsection: '',
    title:
      'Biden Calls on World to Punish Russia for Attempt to Annex Ukrainian Land',
    abstract:
      'The U.S. imposed new sanctions on Russian officials and companies, and penalized foreign businesses aiding the Russian military. But officials are holding back on energy sanctions.',
    url: 'https://www.nytimes.com/2022/09/30/us/biden-putin-russia-ukraine.html',
    uri: 'nyt://article/557e313f-bc38-5e41-9609-181cbf90b805',
    byline: 'By Michael Crowley and Edward Wong',
    item_type: 'Article',
    updated_date: '2022-10-01T07:34:57-04:00',
    created_date: '2022-09-30T19:31:32-04:00',
    published_date: '2022-09-30T19:31:32-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Embargoes and Sanctions',
      'Banking and Financial Institutions',
      'Russian Invasion of Ukraine (2022)',
      'Oil (Petroleum) and Gasoline',
    ],
    org_facet: [
      'Central Bank of Russia',
      'Commerce Department',
      'North Atlantic Treaty Organization',
      'Treasury Department',
    ],
    per_facet: [
      'Biden, Joseph R Jr',
      'Putin, Vladimir V',
      'Zelensky, Volodymyr',
    ],
    geo_facet: ['Russia', 'Ukraine'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/us/politics/30dc-prexy_1/merlin_213780861_2bd8495b-110f-4fad-bc2d-c0c0bcffcc96-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1365,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Residents casting their votes in a referendum in Donetsk, a province of eastern Ukraine that Russia has claimed as part of its territory.',
        copyright: 'Alexander Ermochenko/Reuters',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/us/politics/30dc-prexy_1/merlin_213780861_2bd8495b-110f-4fad-bc2d-c0c0bcffcc96-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'Residents casting their votes in a referendum in Donetsk, a province of eastern Ukraine that Russia has claimed as part of its territory.',
        copyright: 'Alexander Ermochenko/Reuters',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/us/politics/30dc-prexy_1/merlin_213780861_2bd8495b-110f-4fad-bc2d-c0c0bcffcc96-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Residents casting their votes in a referendum in Donetsk, a province of eastern Ukraine that Russia has claimed as part of its territory.',
        copyright: 'Alexander Ermochenko/Reuters',
      },
    ],
    short_url: 'https://nyti.ms/3fxpdSZ',
  },
  {
    section: 'world',
    subsection: 'africa',
    title: 'McKinsey Charged in South African Corruption Case',
    abstract:
      'The South African branch of the global consulting firm has been charged in a corruption scandal related to its work with the country’s state-owned freight rail and port operator.',
    url: 'https://www.nytimes.com/2022/09/30/world/africa/mckinsey-corruption-case-south-africa.html',
    uri: 'nyt://article/862a32c8-a954-5b68-8ed0-45df411b7cb5',
    byline: 'By Michael Forsythe and Walt Bogdanich',
    item_type: 'Article',
    updated_date: '2022-09-30T19:13:37-04:00',
    created_date: '2022-09-30T19:13:37-04:00',
    published_date: '2022-09-30T19:13:37-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: ['Government Contracts and Procurement', 'Money Laundering'],
    org_facet: [
      'McKinsey & Co',
      'National Prosecuting Authority (South Africa)',
    ],
    per_facet: ['Zuma, Jacob G'],
    geo_facet: ['Africa', 'South Africa'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30mckinsey-01-1-ad6b/30mckinsey-01-1-ad6b-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1365,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption: 'The McKinsey & Company offices in Sandton, South Africa.',
        copyright: 'Gulshan Khan for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30mckinsey-01-1-ad6b/30mckinsey-01-1-ad6b-threeByTwoSmallAt2X-v2.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption: 'The McKinsey & Company offices in Sandton, South Africa.',
        copyright: 'Gulshan Khan for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30mckinsey-01-1-ad6b/30mckinsey-01-1-ad6b-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption: 'The McKinsey & Company offices in Sandton, South Africa.',
        copyright: 'Gulshan Khan for The New York Times',
      },
    ],
    short_url: 'https://nyti.ms/3LZNEVq',
  },
  {
    section: 'world',
    subsection: 'europe',
    title: 'With Bluster and Threats, Putin Casts the West as the Enemy',
    abstract:
      'Declaring that Russia would annex four regions of Ukraine, which the West rejects as illegal, the Russian president accused the U.S. and its allies of “despotism’’ and “Satanism.’’',
    url: 'https://www.nytimes.com/2022/09/30/world/europe/putin-speech-ukraine-russia.html',
    uri: 'nyt://article/9cea7023-42df-58cf-941e-222a6f6e650a',
    byline: 'By Anton Troianovski and Valerie Hopkins',
    item_type: 'Article',
    updated_date: '2022-09-30T23:26:53-04:00',
    created_date: '2022-09-30T19:03:12-04:00',
    published_date: '2022-09-30T19:03:12-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Russian Invasion of Ukraine (2022)',
      'Nuclear Weapons',
      'Embargoes and Sanctions',
      'Draft and Recruitment (Military)',
    ],
    org_facet: ['North Atlantic Treaty Organization', 'Security Council (UN)'],
    per_facet: [
      'Putin, Vladimir V',
      'Zelensky, Volodymyr',
      'Biden, Joseph R Jr',
    ],
    geo_facet: ['Russia', 'Moscow (Russia)'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30ukraine-ledeall-new/merlin_214079571_d4df6afe-10d1-4efa-8fc1-146ff16891ce-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1348,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'President Vladimir V. Putin of Russia addressed a rally and concert in Red Square on Friday celebrating Russia’s illegal annexation of four Ukrainian provinces.',
        copyright: 'Alexander Nemenov/Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30ukraine-ledeall-new/30ukraine-ledeall-new-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'President Vladimir V. Putin of Russia addressed a rally and concert in Red Square on Friday celebrating Russia’s illegal annexation of four Ukrainian provinces.',
        copyright: 'Alexander Nemenov/Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30ukraine-ledeall-new/30ukraine-ledeall-new-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'President Vladimir V. Putin of Russia addressed a rally and concert in Red Square on Friday celebrating Russia’s illegal annexation of four Ukrainian provinces.',
        copyright: 'Alexander Nemenov/Agence France-Presse — Getty Images',
      },
    ],
    short_url: 'https://nyti.ms/3riNEWO',
  },
  {
    section: 'world',
    subsection: 'middleeast',
    title: 'Yusuf al-Qaradawi, Influential Muslim Scholar, Dies at 96',
    abstract:
      'Considered a moderate by some and an extremist by others, he backed political Islam, attacked Al Qaeda and dispensed advice in a TV show viewed by millions.',
    url: 'https://www.nytimes.com/2022/09/30/world/middleeast/yusuf-al-qaradawi-dead.html',
    uri: 'nyt://article/5f65e2a8-4865-5c2f-994d-005a96d3fe49',
    byline: '',
    item_type: 'Article',
    updated_date: '2022-09-30T17:50:05-04:00',
    created_date: '2022-09-30T16:53:42-04:00',
    published_date: '2022-09-30T16:53:42-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Deaths (Obituaries)',
      'Muslims and Islam',
      'Shariah (Islamic Law)',
      'Middle East and North Africa Unrest (2010- )',
    ],
    org_facet: ['Al Jazeera', 'Muslim Brotherhood (Egypt)'],
    per_facet: ['Qaradawi, Yusuf al-'],
    geo_facet: ['Egypt', 'Qatar'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/29/obituaries/29alqaradawi-obit/merlin_213840153_5914df89-cf7a-41f2-ad05-5367a3bef6fe-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1365,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Yusuf al-Qaradawi in 2014. He was a popular advocate of political Islam and seen as a threat by Arab autocrats.',
        copyright: 'Karim Jaafar/Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/29/obituaries/29alqaradawi-obit/merlin_213840153_5914df89-cf7a-41f2-ad05-5367a3bef6fe-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'Yusuf al-Qaradawi in 2014. He was a popular advocate of political Islam and seen as a threat by Arab autocrats.',
        copyright: 'Karim Jaafar/Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/29/obituaries/29alqaradawi-obit/merlin_213840153_5914df89-cf7a-41f2-ad05-5367a3bef6fe-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Yusuf al-Qaradawi in 2014. He was a popular advocate of political Islam and seen as a threat by Arab autocrats.',
        copyright: 'Karim Jaafar/Agence France-Presse — Getty Images',
      },
    ],
    short_url: 'https://nyti.ms/3y5Kauw',
  },
  {
    section: 'world',
    subsection: 'europe',
    title:
      'Moscow Pounds Regions in Eastern Ukraine, Then Declares Them Part of Russia',
    abstract:
      'The strikes killed a total of 30 civilians and wounded 107 in one of the bloodiest attacks in recent weeks.',
    url: 'https://www.nytimes.com/2022/09/30/world/europe/russian-strikes-ukraine.html',
    uri: 'nyt://article/ad6ad7b3-ae7e-5315-9d30-d7b53dbabe72',
    byline: 'By Andrew E. Kramer',
    item_type: 'Article',
    updated_date: '2022-10-01T15:10:25-04:00',
    created_date: '2022-09-30T16:00:20-04:00',
    published_date: '2022-09-30T16:00:20-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Russian Invasion of Ukraine (2022)',
      'Civilian Casualties',
      'Defense and Military Forces',
    ],
    org_facet: ['North Atlantic Treaty Organization'],
    per_facet: ['Putin, Vladimir V', 'Zelensky, Volodymyr'],
    geo_facet: [
      'Russia',
      'Ukraine',
      'Donetsk (Ukraine)',
      'Lyman (Ukraine)',
      'Zaporizhzhia (Ukraine)',
    ],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30ukraine-briefing-zaporizhzhia-attack05/merlin_214065375_2bcfa086-375d-4667-9976-181bbd5e41ad-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1366,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Brendan Hoffman for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30ukraine-briefing-zaporizhzhia-attack05/merlin_214065375_2bcfa086-375d-4667-9976-181bbd5e41ad-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Brendan Hoffman for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30ukraine-briefing-zaporizhzhia-attack05/30ukraine-briefing-zaporizhzhia-attack05-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Brendan Hoffman for The New York Times',
      },
    ],
    short_url: 'https://nyti.ms/3Sr1fr5',
  },
  {
    section: 'sports',
    subsection: 'soccer',
    title: 'Arrests and Warnings as Iranian Soccer Stars Take Side in Protests',
    abstract:
      'Some of the country’s most famous players have expressed support for street protests over the death of a young woman. On Thursday, an activist group went further: It asked FIFA to bar Iran from the World Cup.',
    url: 'https://www.nytimes.com/2022/09/30/sports/soccer/iran-soccer-protests.html',
    uri: 'nyt://article/28c97a0e-c4e5-50d6-a31f-1e550ed06a5b',
    byline: 'By Rory Smith and Tariq Panja',
    item_type: 'Article',
    updated_date: '2022-10-01T13:21:49-04:00',
    created_date: '2022-09-30T15:40:40-04:00',
    published_date: '2022-09-30T15:40:40-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Soccer',
      'World Cup 2022 (Soccer)',
      'Demonstrations, Protests and Riots',
    ],
    org_facet: [
      'International Federation of Association Football (FIFA)',
      'Open Stadiums',
    ],
    per_facet: ['Amini, Mahsa (2000-22)', 'Infantino, Gianni'],
    geo_facet: ['Iran'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30soccer-iran-fans-1-31c0/30soccer-iran-fans-1-31c0-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1439,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Iran’s most recent game, against Senegal in Austria, was played behind closed doors after protesters turned up at a match last week.',
        copyright: 'Jakub Sukup/Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30soccer-iran-fans-1-31c0/30soccer-iran-fans-1-31c0-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'Iran’s most recent game, against Senegal in Austria, was played behind closed doors after protesters turned up at a match last week.',
        copyright: 'Jakub Sukup/Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30soccer-iran-fans-1-31c0/30soccer-iran-fans-1-31c0-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Iran’s most recent game, against Senegal in Austria, was played behind closed doors after protesters turned up at a match last week.',
        copyright: 'Jakub Sukup/Agence France-Presse — Getty Images',
      },
    ],
    short_url: 'https://nyti.ms/3SnpztQ',
  },
  {
    section: 'world',
    subsection: 'europe',
    title: 'Biden Declares West Will Not Be Intimidated by Putin’s Actions',
    abstract:
      'The president also said that Mr. Putin should not dare to take his fight into NATO territory, underscoring the unity among the alliance.',
    url: 'https://www.nytimes.com/2022/09/30/world/europe/biden-putin-russia.html',
    uri: 'nyt://article/091a9a0f-a9d0-5beb-b71f-f96a07d72a05',
    byline: 'By Alan Rappeport',
    item_type: 'Article',
    updated_date: '2022-09-30T15:48:04-04:00',
    created_date: '2022-09-30T15:06:26-04:00',
    published_date: '2022-09-30T15:06:26-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'War and Armed Conflicts',
      'Russian Invasion of Ukraine (2022)',
    ],
    org_facet: ['North Atlantic Treaty Organization'],
    per_facet: ['Biden, Joseph R Jr', 'Putin, Vladimir V'],
    geo_facet: ['Russia', 'United States'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30ukraine-briefing-biden-comments-1-2b06/30ukraine-briefing-biden-comments-1-2b06-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1366,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'President Biden said during a news conference at the White House on Friday that the world would not recognize Russia’s annexation efforts.',
        copyright: 'Pete Marovich for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30ukraine-briefing-biden-comments-1-2b06/30ukraine-briefing-biden-comments-1-2b06-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'President Biden said during a news conference at the White House on Friday that the world would not recognize Russia’s annexation efforts.',
        copyright: 'Pete Marovich for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30ukraine-briefing-biden-comments-1-2b06/30ukraine-briefing-biden-comments-1-2b06-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'President Biden said during a news conference at the White House on Friday that the world would not recognize Russia’s annexation efforts.',
        copyright: 'Pete Marovich for The New York Times',
      },
    ],
    short_url: 'https://nyti.ms/3SnobaC',
  },
  {
    section: 'world',
    subsection: 'europe',
    title:
      'E.U. ministers approve taxes on energy profits to support struggling households.',
    abstract: '',
    url: 'https://www.nytimes.com/2022/09/30/world/europe/eu-ministers-approve-taxes-on-energy-profits-to-support-struggling-households.html',
    uri: 'nyt://article/dd66207e-2c09-52d9-8555-cd73f18db1df',
    byline: 'By Monika Pronczuk',
    item_type: 'Article',
    updated_date: '2022-10-01T09:51:08-04:00',
    created_date: '2022-09-30T12:41:34-04:00',
    published_date: '2022-09-30T12:41:34-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [],
    org_facet: [],
    per_facet: [],
    geo_facet: [],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30ukraine-briefing-EU-energy-image/merlin_214064811_1e064a45-2868-4bc2-bcc1-18ab711414a3-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1365,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Kadri Simson, the European commissioner for energy, and Deputy Prime Minister Jozef Sikela of the Czech Republic at a news conference after a European Union Energy Ministers meeting on high energy prices, in Brussels, on Friday.',
        copyright: 'Yves Herman/Reuters',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30ukraine-briefing-EU-energy-image/merlin_214064811_1e064a45-2868-4bc2-bcc1-18ab711414a3-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'Kadri Simson, the European commissioner for energy, and Deputy Prime Minister Jozef Sikela of the Czech Republic at a news conference after a European Union Energy Ministers meeting on high energy prices, in Brussels, on Friday.',
        copyright: 'Yves Herman/Reuters',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30ukraine-briefing-EU-energy-image/30ukraine-briefing-EU-energy-image-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Kadri Simson, the European commissioner for energy, and Deputy Prime Minister Jozef Sikela of the Czech Republic at a news conference after a European Union Energy Ministers meeting on high energy prices, in Brussels, on Friday.',
        copyright: 'Yves Herman/Reuters',
      },
    ],
    short_url: 'https://nyti.ms/3LWN9uX',
  },
  {
    section: 'world',
    subsection: 'middleeast',
    title: 'Iran Protests Continue Despite Heavy Crackdowns',
    abstract:
      'Dozens of people have been killed in nationwide demonstrations that erupted almost two weeks ago after Mahsa Amini, a 22-year-old woman, died in police custody.',
    url: 'https://www.nytimes.com/2022/09/30/world/middleeast/iran-protests-government-crackdown.html',
    uri: 'nyt://article/ddb0b93c-6d8a-57b5-9e2c-e9b878be8844',
    byline: 'By Farnaz Fassihi and Cora Engelbrecht',
    item_type: 'Article',
    updated_date: '2022-10-01T00:52:19-04:00',
    created_date: '2022-09-30T11:33:19-04:00',
    published_date: '2022-09-30T11:33:19-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Demonstrations, Protests and Riots',
      'Muslim Veiling',
      'Kurds',
    ],
    org_facet: [],
    per_facet: ['Amini, Mahsa (2000-22)'],
    geo_facet: ['Iran'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/29/world/29iran-protests/29iran-protests-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1378,
        width: 1335,
        type: 'image',
        subtype: 'photo',
        caption:
          'A photo obtained from social media showing protesters in Sanandaj, the capital of Kurdistan Province, Iran, on Wednesday.',
        copyright: 'via Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/29/world/29iran-protests/29iran-protests-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'A photo obtained from social media showing protesters in Sanandaj, the capital of Kurdistan Province, Iran, on Wednesday.',
        copyright: 'via Agence France-Presse — Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/29/world/29iran-protests/29iran-protests-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'A photo obtained from social media showing protesters in Sanandaj, the capital of Kurdistan Province, Iran, on Wednesday.',
        copyright: 'via Agence France-Presse — Getty Images',
      },
    ],
    short_url: 'https://nyti.ms/3CmtBgm',
  },
  {
    section: 'world',
    subsection: 'americas',
    title: 'Protests Erupt in Cuba Over Government Response to Hurricane Ian',
    abstract:
      'Demonstrators in Havana blocked street traffic, chanting “we want the light.” Many were angry that the lack of electricity this week has rotted what little food they had stored.',
    url: 'https://www.nytimes.com/2022/09/30/world/americas/cuba-hurricane-ian-protests.html',
    uri: 'nyt://article/443abf01-73a1-5be8-bb16-3cd8d5a35294',
    byline: 'By Camila Acosta and Maria Abi-Habib',
    item_type: 'Article',
    updated_date: '2022-10-01T03:53:42-04:00',
    created_date: '2022-09-30T11:25:12-04:00',
    published_date: '2022-09-30T11:25:12-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Demonstrations, Protests and Riots',
      'Politics and Government',
      'Food',
      'Hurricanes and Tropical Storms',
      'Hurricane Ian (2022)',
    ],
    org_facet: [],
    per_facet: [],
    geo_facet: ['Cuba', 'Havana (Cuba)'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30ian-cuba-update-1-00c9/30ian-cuba-update-1-00c9-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1366,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'People gathering in front of a Communist Party office in protest against the electricity shortage in Havana on Thursday.',
        copyright: 'Alexandre Meneghini/Reuters',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30ian-cuba-update-1-00c9/30ian-cuba-update-1-00c9-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'People gathering in front of a Communist Party office in protest against the electricity shortage in Havana on Thursday.',
        copyright: 'Alexandre Meneghini/Reuters',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30ian-cuba-update-1-00c9/30ian-cuba-update-1-00c9-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'People gathering in front of a Communist Party office in protest against the electricity shortage in Havana on Thursday.',
        copyright: 'Alexandre Meneghini/Reuters',
      },
    ],
    short_url: 'https://nyti.ms/3fpTfYB',
  },
  {
    section: 'world',
    subsection: 'europe',
    title:
      'Ukraine submits an application to join NATO, with big hurdles ahead.',
    abstract:
      'Ukraine’s desire to join the alliance has long been a source of conflict with Russia, which sees the eastward expansion of NATO as a existential threat.',
    url: 'https://www.nytimes.com/2022/09/30/world/europe/ukraine-nato-zelensky.html',
    uri: 'nyt://article/d73e065c-f882-5e19-a8c1-e1985c045c8b',
    byline: 'By Andrew E. Kramer and Dan Bilefsky',
    item_type: 'Article',
    updated_date: '2022-09-30T17:19:25-04:00',
    created_date: '2022-09-30T10:28:03-04:00',
    published_date: '2022-09-30T10:28:03-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: ['Russian Invasion of Ukraine (2022)'],
    org_facet: ['North Atlantic Treaty Organization'],
    per_facet: [],
    geo_facet: [],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30ukraine-briefing-nato/merlin_214068015_4184ff0f-941d-49ec-8706-4dff11f62893-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1383,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'A photo provided by the Ukrainian Presidential Press Office of President Volodymyr Zelensky in Kyiv, Ukraine, leading a meeting on national security on Friday.',
        copyright: 'Ukrainian Presidential Press Office, via Associated Press',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30ukraine-briefing-nato/merlin_214068015_4184ff0f-941d-49ec-8706-4dff11f62893-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'A photo provided by the Ukrainian Presidential Press Office of President Volodymyr Zelensky in Kyiv, Ukraine, leading a meeting on national security on Friday.',
        copyright: 'Ukrainian Presidential Press Office, via Associated Press',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30ukraine-briefing-nato/30ukraine-briefing-nato-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'A photo provided by the Ukrainian Presidential Press Office of President Volodymyr Zelensky in Kyiv, Ukraine, leading a meeting on national security on Friday.',
        copyright: 'Ukrainian Presidential Press Office, via Associated Press',
      },
    ],
    short_url: 'https://nyti.ms/3LUEIjQ',
  },
  {
    section: 'arts',
    subsection: 'television',
    title: 'Britain Wonders, Is It Too Soon to Dramatize the Pandemic?',
    abstract:
      'A new Sky Atlantic mini-series, “This England,” depicts the early days of Covid-19 in the country, with Kenneth Branagh playing Boris Johnson.',
    url: 'https://www.nytimes.com/2022/09/30/arts/television/this-england-coronavirus.html',
    uri: 'nyt://article/108b296c-0e87-556a-a8f9-7288d67fd159',
    byline: 'By Mark Landler',
    item_type: 'Article',
    updated_date: '2022-09-30T12:05:10-04:00',
    created_date: '2022-09-30T09:22:57-04:00',
    published_date: '2022-09-30T09:22:57-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Nursing and Nurses',
      'Television',
      'Coronavirus (2019-nCoV)',
      'This England (TV Program)',
    ],
    org_facet: [],
    per_facet: ['Branagh, Kenneth'],
    geo_facet: ['Great Britain'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/arts/30this-england06/merlin_213868140_492ba999-dcca-49bd-8bc5-06a1a498b5dd-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1365,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Phil Fisk/Sky Atlantic',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/arts/30this-england06/30strickland06-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Phil Fisk/Sky Atlantic',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/arts/30this-england06/30strickland06-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Phil Fisk/Sky Atlantic',
      },
    ],
    short_url: 'https://nyti.ms/3dSFPnN',
  },
  {
    section: 'world',
    subsection: 'africa',
    title: 'Military Officers Announce Coup in Burkina Faso',
    abstract:
      'The officers said they had decided to remove the president because of his inability to stem a growing Islamist insurgency in the north and east of the country.',
    url: 'https://www.nytimes.com/2022/09/30/world/africa/burkina-faso-coup.html',
    uri: 'nyt://article/7207fb66-7aaa-50d9-aeb4-c4a4f230ecea',
    byline: 'By Ruth Maclean and Elian Peltier',
    item_type: 'Article',
    updated_date: '2022-10-01T01:13:12-04:00',
    created_date: '2022-09-30T07:19:40-04:00',
    published_date: '2022-09-30T07:19:40-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      "Coups D'Etat and Attempted Coups D'Etat",
      'Politics and Government',
    ],
    org_facet: [],
    per_facet: [],
    geo_facet: ['Ouagadougou (Burkina Faso)'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30burkina-faso-newnew/30burkina-faso-newnew-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1365,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Crowds gathered in protest of the country’s president, Lt. Col. Paul-Henri Sandaogo Damiba, in Ouagadougou, Burkina Faso, on Friday.',
        copyright: 'Sophie Garcia/Associated Press',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30burkina-faso-newnew/30burkina-faso-newnew-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'Crowds gathered in protest of the country’s president, Lt. Col. Paul-Henri Sandaogo Damiba, in Ouagadougou, Burkina Faso, on Friday.',
        copyright: 'Sophie Garcia/Associated Press',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30burkina-faso-newnew/30burkina-faso-newnew-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Crowds gathered in protest of the country’s president, Lt. Col. Paul-Henri Sandaogo Damiba, in Ouagadougou, Burkina Faso, on Friday.',
        copyright: 'Sophie Garcia/Associated Press',
      },
    ],
    short_url: 'https://nyti.ms/3fyxohF',
  },
  {
    section: 'world',
    subsection: 'europe',
    title:
      'Despite international condemnation, Putin signs decrees declaring four regions of Ukraine part of Russia.',
    abstract: '',
    url: 'https://www.nytimes.com/2022/09/30/world/europe/putin-is-set-to-declare-that-four-regions-of-ukraine-are-part-of-russia-despite-international-condemnation.html',
    uri: 'nyt://article/b0be5b29-61af-5e5a-838a-bb1a9e5c9db6',
    byline: 'By Anton Troianovski, Andrew E. Kramer and Dan Bilefsky',
    item_type: 'Article',
    updated_date: '2022-09-30T10:04:20-04:00',
    created_date: '2022-09-30T06:57:28-04:00',
    published_date: '2022-09-30T06:57:28-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [],
    org_facet: [],
    per_facet: [],
    geo_facet: [],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30ukraine-briefing-putin-annexation-image2-1-7d58/30ukraine-briefing-putin-annexation-image2-1-7d58-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1448,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'President Vladimir V. Putin of Russia giving a speech during a ceremony at the Kremlin in Moscow on Friday.',
        copyright: 'Gavriil Grigorov/Agence France-Presse, via Sputnik ',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30ukraine-briefing-putin-annexation-image2-1-7d58/30ukraine-briefing-putin-annexation-image2-1-7d58-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'President Vladimir V. Putin of Russia giving a speech during a ceremony at the Kremlin in Moscow on Friday.',
        copyright: 'Gavriil Grigorov/Agence France-Presse, via Sputnik ',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30ukraine-briefing-putin-annexation-image2-1-7d58/30ukraine-briefing-putin-annexation-image2-1-7d58-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'President Vladimir V. Putin of Russia giving a speech during a ceremony at the Kremlin in Moscow on Friday.',
        copyright: 'Gavriil Grigorov/Agence France-Presse, via Sputnik ',
      },
    ],
    short_url: 'https://nyti.ms/3Cmt7qI',
  },
  {
    section: 'briefing',
    subsection: '',
    title: 'Gerrymandering, the Full Story',
    abstract:
      'A Times analysis finds that the House of Representative has its fairest map in 40 years, despite recent gerrymandering.',
    url: 'https://www.nytimes.com/2022/09/30/briefing/gerrymandering-maps-districts-republicans-democrats.html',
    uri: 'nyt://article/3634a544-56b8-5f63-ae64-22f057936c46',
    byline: 'By David Leonhardt',
    item_type: 'Article',
    updated_date: '2022-09-30T06:43:32-04:00',
    created_date: '2022-09-30T06:43:04-04:00',
    published_date: '2022-09-30T06:43:04-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'internal-storyline-no',
      'Midterm Elections (2022)',
      'Politics and Government',
      'Redistricting and Reapportionment',
      'Polls and Public Opinion',
    ],
    org_facet: [],
    per_facet: [],
    geo_facet: [],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30-THE-MORNING-NL-ukzgm-1-0744/30-THE-MORNING-NL-ukzgm-1-0744-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 2048,
        width: 1640,
        type: 'image',
        subtype: 'photo',
        caption:
          'Congressional gerrymandering is a smaller problem than it has been for much of the recent past.',
        copyright: 'Haiyun Jiang/The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30-THE-MORNING-NL-ukzgm-1-0744/30-THE-MORNING-NL-ukzgm-1-0744-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'Congressional gerrymandering is a smaller problem than it has been for much of the recent past.',
        copyright: 'Haiyun Jiang/The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/multimedia/30-THE-MORNING-NL-ukzgm-1-0744/30-THE-MORNING-NL-ukzgm-1-0744-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Congressional gerrymandering is a smaller problem than it has been for much of the recent past.',
        copyright: 'Haiyun Jiang/The New York Times',
      },
    ],
    short_url: 'https://nyti.ms/3CmC5nZ',
  },
  {
    section: 'world',
    subsection: 'asia',
    title: 'Thai Prime Minister Can Stay in Power, Constitutional Court Rules',
    abstract:
      'The former general seized power in a 2014 coup. The opposition had argued that the Constitution stipulated he leave office this year.',
    url: 'https://www.nytimes.com/2022/09/30/world/asia/thailand-prime-minister.html',
    uri: 'nyt://article/8d632feb-1cef-5710-bd65-53161871f6d0',
    byline: 'By Sui-Lee Wee and Ryn Jirenuwat',
    item_type: 'Article',
    updated_date: '2022-10-01T01:12:14-04:00',
    created_date: '2022-09-30T06:21:54-04:00',
    published_date: '2022-09-30T06:21:54-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Politics and Government',
      'Decisions and Verdicts',
      "Coups D'Etat and Attempted Coups D'Etat",
      'Royal Families',
      'Demonstrations, Protests and Riots',
      'Constitutions',
    ],
    org_facet: [],
    per_facet: ['Prayuth Chan-ocha'],
    geo_facet: ['Thailand', 'Bangkok (Thailand)'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30thailand-01/merlin_214043967_df37a575-2f82-4c97-8c16-359386dbb5df-superJumbo.jpg',
        format: 'Super Jumbo',
        height: 1365,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Prime Minister Prayuth Chan-ocha of Thailand. During his eight years in power, he has survived four no-confidence votes.',
        copyright: 'Sakchai Lalit/Associated Press',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30thailand-01/merlin_214043967_df37a575-2f82-4c97-8c16-359386dbb5df-threeByTwoSmallAt2X.jpg',
        format: 'threeByTwoSmallAt2X',
        height: 400,
        width: 600,
        type: 'image',
        subtype: 'photo',
        caption:
          'Prime Minister Prayuth Chan-ocha of Thailand. During his eight years in power, he has survived four no-confidence votes.',
        copyright: 'Sakchai Lalit/Associated Press',
      },
      {
        url: 'https://static01.nyt.com/images/2022/09/30/world/30thailand-01/merlin_214043967_df37a575-2f82-4c97-8c16-359386dbb5df-thumbLarge.jpg',
        format: 'Large Thumbnail',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Prime Minister Prayuth Chan-ocha of Thailand. During his eight years in power, he has survived four no-confidence votes.',
        copyright: 'Sakchai Lalit/Associated Press',
      },
    ],
    short_url: 'https://nyti.ms/3Cj3FT1',
  },
];
